[collection_workflow]
data_collection_tool = """  """
data_collection_year = """  """
feature_extraction_tool_info = """ Tool that converts dataset to feature dataset. If any. """
feature_extraction_tool = """  """
feature_extraction_tool_description = """  """
capture_config_parameters_info = """ specific parameters that were used to capture dataset or feature dataset """
capture_config_parameters = """  """
real_dataset_info = """ Source of the dataset. E.g., real environment, testbed or generated. """
real_dataset = """  """
annotation_info = """ Description of the dataset annotation. E.g., manual, automatic """
annotation = """  """

[generic_info]
capture_dates_info = """ When was the dataset captured/generated """
capture_dates = """ n/a """
classes = """ 160 """
features = """ 134 """
f1-score_info = """ F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM] """
f1-score = """ 0.7914038260485151 """
performance_metric_info = """ Perfomance metric defined by the author. Please define full specification e.g., F1-weighted """
performance_metric_name = """  """
performance_metric_value = """  """
label_info = """ Name of the field with label. In case this is unsupervised dataset, type None """
label = """  """
known_issues_info = """ Description of indentified issues in the dataset """
known_issues = """   """
key_observations_info = """ List of known errors, drifts, limits, ... of the dataset """
key_observations = """  * The dataset has 1 small classes, 86671 duplicated samples, 0 nan value """
dataset_organization_info = """ Structure of the dataset. E.g., per day, per capture, per device """
dataset_organization = """  """
dataset_organization_description_info = """ Description of the content of the organization. Is there any metadata? """
dataset_organization_description = """   """
dataset_documentation_info = """ How to get started with the dataset. Ideally add example notebook. """
dataset_documentation = """   """
used_dataset_info = """ Script to get dataset for provided analysis """
used_dataset = """ get-dataset.py """
dataset_application_info = """ Where the dataset has been already applied. """
dataset_application = """   """
per_class_data = """{
  "52": "5875",
  "91": "5835",
  "87": "5587",
  "136": "5405",
  "106": "5356",
  "23": "5061",
  "110": "4635",
  "125": "4438",
  "139": "4204",
  "120": "4149",
  "116": "4116",
  "77": "3790",
  "90": "3693",
  "85": "3662",
  "16": "3509",
  "63": "3206",
  "112": "3202",
  "88": "3107",
  "53": "3010",
  "89": "2859",
  "142": "2757",
  "129": "2750",
  "44": "2617",
  "118": "2461",
  "104": "2417",
  "86": "2392",
  "83": "1996",
  "27": "1901",
  "60": "1875",
  "54": "1864",
  "74": "1830",
  "123": "1761",
  "55": "1705",
  "157": "1624",
  "69": "1601",
  "28": "1597",
  "119": "1581",
  "84": "1550",
  "26": "1514",
  "78": "1473",
  "75": "1387",
  "21": "1311",
  "17": "1287",
  "141": "1270",
  "134": "1249",
  "127": "1145",
  "48": "1111",
  "42": "1025",
  "25": "1015",
  "1": "1009",
  "99": "959",
  "153": "937",
  "49": "890",
  "80": "876",
  "150": "825",
  "40": "812",
  "13": "799",
  "121": "786",
  "117": "751",
  "34": "745",
  "46": "730",
  "148": "729",
  "70": "724",
  "22": "715",
  "2": "696",
  "32": "684",
  "51": "654",
  "41": "612",
  "94": "575",
  "135": "573",
  "65": "568",
  "67": "551",
  "154": "513",
  "71": "511",
  "15": "476",
  "156": "473",
  "58": "459",
  "149": "450",
  "43": "432",
  "5": "403",
  "103": "394",
  "47": "382",
  "124": "382",
  "115": "375",
  "113": "371",
  "82": "368",
  "81": "367",
  "64": "367",
  "105": "366",
  "133": "359",
  "130": "359",
  "37": "357",
  "102": "348",
  "114": "346",
  "131": "346",
  "36": "343",
  "20": "339",
  "128": "335",
  "107": "330",
  "108": "316",
  "24": "313",
  "6": "306",
  "158": "305",
  "29": "303",
  "50": "302",
  "95": "301",
  "96": "298",
  "152": "294",
  "155": "288",
  "57": "286",
  "92": "284",
  "144": "284",
  "68": "282",
  "122": "281",
  "140": "280",
  "38": "268",
  "76": "262",
  "18": "258",
  "66": "256",
  "138": "254",
  "109": "253",
  "98": "251",
  "4": "249",
  "12": "247",
  "97": "247",
  "59": "247",
  "39": "246",
  "147": "234",
  "126": "234",
  "111": "207",
  "101": "206",
  "146": "205",
  "33": "199",
  "143": "198",
  "132": "196",
  "7": "194",
  "151": "185",
  "35": "171",
  "45": "171",
  "19": "167",
  "100": "167",
  "137": "163",
  "56": "147",
  "93": "147",
  "11": "144",
  "61": "143",
  "72": "139",
  "159": "123",
  "10": "122",
  "14": "119",
  "73": "117",
  "9": "109",
  "8": "91",
  "145": "89",
  "3": "89",
  "31": "72",
  "62": "62",
  "30": "53",
  "0": "46",
  "79": "14"
}"""
per_feature_data = """{
  "IPT_1": "",
  "IPT_2": "",
  "IPT_3": "",
  "IPT_4": "",
  "IPT_5": "",
  "IPT_6": "",
  "IPT_7": "",
  "IPT_8": "",
  "IPT_9": "",
  "IPT_10": "",
  "IPT_11": "",
  "IPT_12": "",
  "IPT_13": "",
  "IPT_14": "",
  "IPT_15": "",
  "IPT_16": "",
  "IPT_17": "",
  "IPT_18": "",
  "IPT_19": "",
  "IPT_20": "",
  "IPT_21": "",
  "IPT_22": "",
  "IPT_23": "",
  "IPT_24": "",
  "IPT_25": "",
  "IPT_26": "",
  "IPT_27": "",
  "IPT_28": "",
  "IPT_29": "",
  "IPT_30": "",
  "DIR_1": "",
  "DIR_2": "",
  "DIR_3": "",
  "DIR_4": "",
  "DIR_5": "",
  "DIR_6": "",
  "DIR_7": "",
  "DIR_8": "",
  "DIR_9": "",
  "DIR_10": "",
  "DIR_11": "",
  "DIR_12": "",
  "DIR_13": "",
  "DIR_14": "",
  "DIR_15": "",
  "DIR_16": "",
  "DIR_17": "",
  "DIR_18": "",
  "DIR_19": "",
  "DIR_20": "",
  "DIR_21": "",
  "DIR_22": "",
  "DIR_23": "",
  "DIR_24": "",
  "DIR_25": "",
  "DIR_26": "",
  "DIR_27": "",
  "DIR_28": "",
  "DIR_29": "",
  "DIR_30": "",
  "SIZE_1": "",
  "SIZE_2": "",
  "SIZE_3": "",
  "SIZE_4": "",
  "SIZE_5": "",
  "SIZE_6": "",
  "SIZE_7": "",
  "SIZE_8": "",
  "SIZE_9": "",
  "SIZE_10": "",
  "SIZE_11": "",
  "SIZE_12": "",
  "SIZE_13": "",
  "SIZE_14": "",
  "SIZE_15": "",
  "SIZE_16": "",
  "SIZE_17": "",
  "SIZE_18": "",
  "SIZE_19": "",
  "SIZE_20": "",
  "SIZE_21": "",
  "SIZE_22": "",
  "SIZE_23": "",
  "SIZE_24": "",
  "SIZE_25": "",
  "SIZE_26": "",
  "SIZE_27": "",
  "SIZE_28": "",
  "SIZE_29": "",
  "SIZE_30": "",
  "BYTES": "",
  "BYTES_REV": "",
  "PACKETS": "",
  "PACKETS_REV": "",
  "DURATION": "",
  "PPI_LEN": "",
  "PPI_ROUNDTRIPS": "",
  "PPI_DURATION": "",
  "FLOW_ENDREASON_IDLE": "",
  "FLOW_ENDREASON_ACTIVE": "",
  "FLOW_ENDREASON_END": "",
  "FLOW_ENDREASON_OTHER": "",
  "PSIZE_BIN1": "",
  "PSIZE_BIN2": "",
  "PSIZE_BIN3": "",
  "PSIZE_BIN4": "",
  "PSIZE_BIN5": "",
  "PSIZE_BIN6": "",
  "PSIZE_BIN7": "",
  "PSIZE_BIN8": "",
  "PSIZE_BIN1_REV": "",
  "PSIZE_BIN2_REV": "",
  "PSIZE_BIN3_REV": "",
  "PSIZE_BIN4_REV": "",
  "PSIZE_BIN5_REV": "",
  "PSIZE_BIN6_REV": "",
  "PSIZE_BIN7_REV": "",
  "PSIZE_BIN8_REV": "",
  "IPT_BIN1": "",
  "IPT_BIN2": "",
  "IPT_BIN3": "",
  "IPT_BIN4": "",
  "IPT_BIN5": "",
  "IPT_BIN6": "",
  "IPT_BIN7": "",
  "IPT_BIN8": "",
  "IPT_BIN1_REV": "",
  "IPT_BIN2_REV": "",
  "IPT_BIN3_REV": "",
  "IPT_BIN4_REV": "",
  "IPT_BIN5_REV": "",
  "IPT_BIN6_REV": "",
  "IPT_BIN7_REV": "",
  "IPT_BIN8_REV": "",
  "APP": ""
}"""

[dataset_drift_analysis]

[advanced_metrics]
description = """  """
perqoda_permutation_slope = """ 0.6731639121419686 """
p_value_status = """ Good """
redundancy = """ 0.1796875 """
similarity = """ 1.6875454793460116 """
advanced_metrics_workflow = """ dataset-metrics.json """

[dataset_comparison]
description = """ ML model comparison for this dataset """
use_case = """   """
similar_dataset = """   """
